### ISSUE TITLE
[0.1.5+1.19.3] Recursively Addable Modifiers

### ISSUE THREAD

**Issue by Maloonkey** [fzzyhmstrs/gearifiers#1]
By recrafting armor (for example, leather) you can keep adding new modifiers. I'm assuming this is not intentional, especially considering the existence of the reroll altar.

![javaw_1epQKtc3RH](https://user-images.githubusercontent.com/31419110/221698864-06acce90-9cee-4917-958a-969f71077c6d.png)
![javaw_xUPLHl8qC2](https://user-images.githubusercontent.com/31419110/221698870-c845a532-7961-4bc0-9ff6-63583fd88a60.png)

**Comment by fzzyhmstrs** [comment]
This is fixed in 0.2.0+1.19.3. Modifiers will now reroll like the reroll altar. This is still a bit strong with certain things like the bee hat, but I think I'm ok with that behavior overall.
