### ISSUE TITLE
Gear gets rerolled when used on a smithing table.

### ISSUE THREAD

**Issue by CocoManiaDX** [fzzyhmstrs/gearifiers#10]
Running latest version for Fabric 1.19.2

Not sure if this is a bug or a feature. But upgrading diamond armor/tools to netherite on the smithing table rerolls the modifiers as if crafting a new item instead of keeping the modifier of the item you're upgrading.

![sword_upgrade](https://github.com/fzzyhmstrs/gearifiers/assets/112061622/a4423495-6a92-425a-840f-c9d643b52526)

This also happens with modded armors/tools that use the smithing table upgrade system as a crafting method.

Still, loving the mod. So just thought I'd report this if it wasn't intended.
Thank ya :)

**Comment by fzzyhmstrs** [comment]
Hi, this is intended. They are new items, and it's supposed to be a new risk and reward to upgrading the gear.

**Comment by jozzo402** [comment]
> Hi, this is intended. They are new items, and it's supposed to be a new risk and reward to upgrading the gear.

Could this be made into a config option instead? This feature isn't super disruptive in vanilla, but when used with some other mods (eg. Advanced Netherite) it means that you lose your modifier 5 times over the course of upgrading a single armor piece.

**Comment by fzzyhmstrs** [comment]
Sure, I can consider that.
