### ISSUE TITLE
Mass creation items do not get a modifier 

### ISSUE THREAD

**Issue by Naanachi** [fzzyhmstrs/gearifiers#11]
https://github.com/fzzyhmstrs/gearifiers/assets/85463975/ed355777-f18b-43ac-9d42-cf1d5db52450

fabric 1.19.2 mod version 0.3.0

I dont wanna remove xp requirement, so making alot of items as an alternative with shiftclick, I expect them all to have a modifier, but none of the newly created items have one

**Comment by fzzyhmstrs** [comment]
I cannot replicate this in 1.19.2. Do you have some mod installed that messes with how shift-crafting works? My test with wooden swords crafted from the crafting table all at once with shift-click
![image](https://github.com/fzzyhmstrs/gearifiers/assets/72876796/1d02e3c3-d69d-4305-a0ad-fd3f58f610a1)
![image](https://github.com/fzzyhmstrs/gearifiers/assets/72876796/561db9f2-69fd-43c7-bd1f-b250965f2e92)
![image](https://github.com/fzzyhmstrs/gearifiers/assets/72876796/9f5a8d86-765b-4541-9fae-7a5b3f276e6a)

**Comment by Naanachi** [comment]
might have been a crafting table mod i have downloaded, im not home at the moment and i will see what could be causing the issue
