### ISSUE TITLE
(Feature Request) Config option to prevent entities equipping dropped items adding more modifiers

### ISSUE THREAD

**Issue by TheRealIceCracker** [fzzyhmstrs/gearifiers#16]
As it stands, every time an item is dropped, picked up by an entity (like a zombie), and then dropped again due to killing the zombie, it rolls more modifiers. This can really quickly brick an item or be used to farm a ridiculously OP item if you get lucky. I'm still not sure if it's actually a good "punishment" for dying from a balance perspective, but regardless of which side someone lands on this issue, it would be nice to have a config option to disable this behavior, if that's technically feasible.

**Comment by fzzyhmstrs** [comment]
Hi, this is unintentional behavior I didn't previously know about, I don't want this to be a possibility config or no, so I will work on a fix.

I have purposeful ways I want people using to add modifiers (seals, rerolling). Using a zombie spawner or whatever is not one of them.

**Comment by chrissquid** [comment]
I think this issue is related but I'm not 100% sure. Every time you die with something equipped in one of the slots added by the Trinkets mod, more modifiers are added to it. It might also counts as being dropped by an entity holding it the same way the zombie issue is happening

**Comment by fzzyhmstrs** [comment]
Fixed in latest versions
