### ISSUE TITLE
endless adding more effects on each death

### ISSUE THREAD

**Issue by Surpos0** [fzzyhmstrs/gearifiers#21]
when player die with something in trinket slot, this item will be given new effect plus old one, and this is stacking endlessly

**Comment by fzzyhmstrs** [comment]
Please provide the versions of mods you are playing with.

When you say stacking do you mean
1) Trinkets has Modifier ABC. When you die it gains it again, so you have "ABC, ABC", "ABC, ABC, ABC" etc
2) Tinket had Modifier ABC, when you die it gains the random modifier DEF, so you have "ABC, DEF", "ABC, DEF, GHI" etc

**Comment by Surpos0** [comment]
2

**Comment by Surpos0** [comment]
I will make you a video showcasing bug and other details but not now cuz im in bed

**Comment by Surpos0** [comment]
Sry

**Comment by Surpos0** [comment]
https://youtu.be/2EG_ELwsu2E
i tested it with jewelry and i think that it causes this bug.

**Comment by fzzyhmstrs** [comment]
Fixed in latest versions
