### ISSUE TITLE
experienced effect bug

### ISSUE THREAD

**Issue by Surpos0** [fzzyhmstrs/gearifiers#22]
when you have on something experienced effect it will give you 0,25 exp every tick.

**Comment by fzzyhmstrs** [comment]
"Experienced" and the others like it are modifiers from *Imbued Gear*.

I tried a ring with "Very Experienced" (first one of that kind I rolled), and wasn't gaining XP every tick.  It might be another mod conflicting or causing some issue with the experience gain somehow.
![image](https://github.com/fzzyhmstrs/gearifiers/assets/72876796/e083ae74-c551-42c8-bb7a-274f3bce6a2e)
