### ISSUE TITLE
Tools are duplicated when combined in player inventory

### ISSUE THREAD

**Issue by numbskul** [fzzyhmstrs/gearifiers#23]
When combining two damaged tools in the player inventory, the combined items don't disappear, giving an extra copy of the tool.

This should be easy to reproduce, take 2 damaged tools and attempt to combine them in the player inventory, the damaged tools disappear visually but can still be interacted with and return to the inventory when the menu is closed.

This only occurs in the player inventory and not a crafting table, and adding "net.minecraft.screen.PlayerScreenHandler" to blacklisted screen handlers didn't fix the issue.

The only mods installed are the fabric API, fabric language Kotlin, and the latest version of fzzy-core, gear-core, and gearifiers, and I was using the latest version of Fabric loader for 1.20.1

Here's the logs, if this helps: [latest.log](https://github.com/fzzyhmstrs/gearifiers/files/13290648/latest.log)
Thank you for your work & let me know if I can help!

**Comment by fzzyhmstrs** [comment]
Thank you for the report! We've been trying to identify the source of this bug on our server for a bit now; this was it. Update is out with a fix.
