### ISSUE TITLE
Gearifiers Reroll Altar bugged

### ISSUE THREAD

**Issue by ereese99** [fzzyhmstrs/gearifiers#5]
Reroll altar saying I dont have enough XP or item is blacklisted when I have 16 levels (5 required) and the item is not blacklisted.

**Comment by fzzyhmstrs** [comment]
Are you using the reroll ingredient needed for the item? If you have REI installed, it should show up in there. I cn't replicate an issue on my end, if I have the right recipe and enough XP it goes through

**Comment by ereese99** [comment]
It was the reroll ingredient that was wrong, my bad!
